POST http://localhost:8000/api/music-task/register
Accept: application/json
Content-Type: application/json

{
  "name": "Alejandro ",
  "lastname": "Castro",
  "email": "alejo@example.com",
  "password": "1234"
}

### login


POST http://localhost:8000/api/music-task/login
Accept: application/json
Content-Type: application/json

{
"email": "mariana@example.com",
"password": "1234"
}

### crear task

POST http://localhost:8000/api/music-task/create
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NDY0NzE4MTAsImV4cCI6MTc0NjQ3NTQxMCwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoiYWxlam9AZXhhbXBsZS5jb20ifQ.hvGfbLa9YYlqGlYXPbNdnlH9IWKSOKEtHrYUew0G9ARraXWqoXILBgRKUlgPsTYvCV05RETKa_Uua_koii9eNrMTEsdaClf769Sno_bkqa8npB-KiuRzO1mqb_RP53cFUFSZZ1HLovyfuLmnTaLl-yLq_sertKUY8Xn9KawGyQEN-Xl1vYchYcqTu3v-aR1HRAknr2LU1A6Rzttl_sdcSj8f9Pm8_C5vmmmnMGGCHq-6O-mYovo4hzj15633cwvlhjW3--IcfwqAyTDj2wNkQH9pdXAf0bQmcDLNNAVspS8g_ExMkKVpl4RcjDwD-D4q023QU9IZosvLB1Ad5jAr8w

{
  "title": "escala jazz show ",
  "description": "Revisar cómo funcionan los validadores personalizados y el Authenticator",
  "estimatedTime": "2024-06-30T14:00:00",
  "date": "2024-06-30T10:00:00",
  "category": "Technique",
  "completed": false
}


### mostrar todas las tareas de un usuario autenticado

GET http://localhost:8000/api/music-task/find
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NDY3MjcyMDMsImV4cCI6MTc0NjczMDgwMywicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoibWFyaWFuYUBleGFtcGxlLmNvbSJ9.YouKzwZSVs4bm1jLXlOCJqXvrusByfdOKWdmeuPDbP6TFRJHi8hKhtWQ93pqyN1qSUAi__WVf4OO1n5-aEPE9JdxJ8zR2nfCtaLZmjzTyl8V-2fJZZI2SKJYNCC0dTc-Se3dk1H8ARW-UsNjfItJEMeZEnin4ZZaB76tRuHAN8QaDZNPOnFr9aNyD0q6LUYSUMZPRj8Cy6AWslEUJ-CsjMZoLtRkKHEHXHu1r7JdemXwWt9nJ5gSlFR7Fg8E-q5HRYnodxnRPyH8D4JNdc4kaZFPDIeAh3Yu9qSXqHuXICXhkU42ANcciUfUQMmJH3NWK_1PbRMNn0ExvkdYbht3-w


### mostrar todas las tareas de un usuario autenticado

GET http://localhost:8000/api/music-task/find/13
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NDY0ODQ1NzgsImV4cCI6MTc0NjQ4ODE3OCwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoiYWxlam9AZXhhbXBsZS5jb20ifQ.nKZQXm1vmURnA48oey2o9FGSHYtur05gk2TeYjWuHDSq5Q9tjRVW50PzHOM7nJVoEEmHT9pEsf0ijVj5XPXnmqltyHPLoEuFGaI2b_bO9HXMvG4DIBaoHd1fQyCj6UNgODKzZy9JOrF0WbXqcj3FGVbTNzjOZzcSgMZepAjbXAP8p7y5WBRy1F57sIFKrcsMHVACachLAKkM7rz-K_5TFmZ6DjfzwE64lky_Fsk5C8jR9XaAZyp2Gpsc2UjVe-Lf1cmmRdEdoHXwWQZ2i2OY7yTLP-kvK_IxTMbb_htiR2GrcLShzbBJ-m7xRz5noouZ2ZRSEnTVioM3m994Rxm2SA

### actualizar una tarea

PUT http://localhost:8000/api/music-task/update/10
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NDY0ODQ1NzgsImV4cCI6MTc0NjQ4ODE3OCwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoiYWxlam9AZXhhbXBsZS5jb20ifQ.nKZQXm1vmURnA48oey2o9FGSHYtur05gk2TeYjWuHDSq5Q9tjRVW50PzHOM7nJVoEEmHT9pEsf0ijVj5XPXnmqltyHPLoEuFGaI2b_bO9HXMvG4DIBaoHd1fQyCj6UNgODKzZy9JOrF0WbXqcj3FGVbTNzjOZzcSgMZepAjbXAP8p7y5WBRy1F57sIFKrcsMHVACachLAKkM7rz-K_5TFmZ6DjfzwE64lky_Fsk5C8jR9XaAZyp2Gpsc2UjVe-Lf1cmmRdEdoHXwWQZ2i2OY7yTLP-kvK_IxTMbb_htiR2GrcLShzbBJ-m7xRz5noouZ2ZRSEnTVioM3m994Rxm2SA


{
  "title": "escala soul show ",
  "description": "Revisar cómo funcionan los validadores personalizados y el Authenticator",
  "estimatedTime": "2024-06-30T14:00:00",
  "date": "2024-06-30T10:00:00",
  "category": "Technique"
}

### borrar una tarea

DELETE http://localhost:8000/api/music-task/delete/5
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NDY0ODc5MDAsImV4cCI6MTc0NjQ5MTUwMCwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoibWFyaWFuYUBleGFtcGxlLmNvbSJ9.nkaTcCaH5jWr3x9RpUcc48h7snU3jOwhSoPlXrEUR2B20JtbsZjSkTLiTezZOVGMu4NQtj88XAD-qIwmTKKr0oGON-LMrJCwGwblUfsBQcEtJPfwLpvDoAKwZStZcoTDybCitd9dranFkeRt-IZuiOXMzUAVTQQeTRyyOFD-q1CL9gIA14IqG56iEvj8rhR4HS_A1HhlAJKJzzqiY-A-jFDJZ7fMZDRv1osO21S4EUs-7_MxL_HiYNXEXdmfTXcxciBBU9uV2Wvp4rP155c5vxcRiH_X5GcjQe_4LVfvIXwuGuZf0hws9u4kMrbSh8KK63ACmVirD7AKSZ8Zl-V8IQ

### recuperar todos los usuairos

GET http://localhost:8000/api/music-task/users
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NDY0ODc5MDAsImV4cCI6MTc0NjQ5MTUwMCwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoibWFyaWFuYUBleGFtcGxlLmNvbSJ9.nkaTcCaH5jWr3x9RpUcc48h7snU3jOwhSoPlXrEUR2B20JtbsZjSkTLiTezZOVGMu4NQtj88XAD-qIwmTKKr0oGON-LMrJCwGwblUfsBQcEtJPfwLpvDoAKwZStZcoTDybCitd9dranFkeRt-IZuiOXMzUAVTQQeTRyyOFD-q1CL9gIA14IqG56iEvj8rhR4HS_A1HhlAJKJzzqiY-A-jFDJZ7fMZDRv1osO21S4EUs-7_MxL_HiYNXEXdmfTXcxciBBU9uV2Wvp4rP155c5vxcRiH_X5GcjQe_4LVfvIXwuGuZf0hws9u4kMrbSh8KK63ACmVirD7AKSZ8Zl-V8IQ
